axoniq:
  axonserver:
    cluster-template:
      users: []
      replicationGroups:
        - roles:
            - role: PRIMARY
              node: axonserver-enterprise-1
            - role: PRIMARY
              node: axonserver-enterprise-2
            - role: PRIMARY
              node: axonserver-enterprise-3
          name: _admin
          contexts:
            - name: _admin
              metaData:
                event.index-format: JUMP_SKIP_INDEX
                snapshot.index-format: JUMP_SKIP_INDEX
        - roles:
            - role: PRIMARY
              node: axonserver-enterprise-2
            - role: PRIMARY
              node: axonserver-enterprise-1
            - role: PRIMARY
              node: axonserver-enterprise-3
          name: tenant-one
          contexts:
            - name: tenant-one
              metaData:
                event.index-format: JUMP_SKIP_INDEX
                snapshot.index-format: JUMP_SKIP_INDEX
      applications: []
      first: axonserver-enterprise-1:8224
