version: '3.3'
services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-distributed-exceptions

networks:
  axon-distributed-exceptions:
